### ISSUE TITLE
Auction provider called prematurely on pubfood refresh

### ISSUE THREAD

**Issue by elljoh** [pubfood/pubfood#21]
When the `pubfood.refresh(slotNameArray)` function is called, it is possible that the auction provider `refresh` method is called before all bid provider `done()` callbacks are made.

It has been observed that bid provider `done()` callbacks are honored on `pubfood.start()`, but not on `pubfood.refresh(...)`. Bids of some providers make it into the subsequent auction provider request, but others not.

**Comment by premesh** [comment]
Definitely causing issues for us on our setup which is live on prod now.  Would love to get a fix in for this. Happy to look into it if you can point me in the right direction!

**Comment by elljoh** [comment]
@premesh I'm finishing up an image carousel example and am planning to make a PR in the next couple of days, if not sooner, to close this issue and provide more coverage for the refresh feature.

**Comment by premesh** [comment]
great!


*Premesh Purayil*

*Chief Technology Officer | www.ranker.com <http://www.ranker.com>*

*o : (323)782-8818 ext 113 | c : (858)382-8745*

**Comment by elljoh** [comment]
@premesh as you would see above, #23 will close this issue (#21), but I'd like you to take a look at the refresh example for any issues/concerns you might have with your `refresh` use cases before working through the merge:
 - https://github.com/pubfood/pubfood/blob/auction-refresh/examples/provider/auction/google/refresh-bid.html
