### ISSUE TITLE
Which bidding and auction partners are compatible?

### ISSUE THREAD

**Issue by diegocgaona** [pubfood/pubfood#22]
Is there a list of the bidding and auction partners? Is there instructions about how to configure each, and where is the js for each one?
I only found one more complete example (https://github.com/pubfood/pubfood/blob/master/examples/literate.js|), but it don't have much partners and uses GTM, and not directly DFP. There is more examples like this?

Thanks a lot!!

**Comment by elljoh** [comment]
@diegocgaona 

## Example starting point
the best place to start for examples is probably the pubfood site page:
 - http://pubfood.org/quick-start

### Other examples
Additionally there is the `pubfood/examples` repo with some standard examples:
 - https://github.com/pubfood/examples/blob/master/public/minimal.html
 - https://github.com/pubfood/examples/blob/master/public/small.html

I caution b/c I am linking to PRs, but these examples will be part of the `pubfood/pubfood` examples proper when they merge:
 - https://github.com/pubfood/pubfood/blob/page-level-bidding/examples/provider/bid/yieldbot/page-level.html
 - https://github.com/pubfood/pubfood/blob/auction-refresh/examples/provider/auction/google/refresh-bid.html

## Partner support in pubfood
The pubfood library can be viewed as a framework for orchestrating partner integration; so in principle, any partner can be supported. A "`contrib`" library of "_partner like_"  example implementations is a goal. At this current time however, the project has not built out an extensive library of `AuctionProvider` and `BidProvider` implementations.

The examples linked above should highlight the basic approach that pubfood takes to delegate bidding partner and auction partner requests to specific publisher use case code. What I see in practice, is that while we can enumerate pretty easily the auction/bid partners out there, the actual implementations for these partners tend to be quite different as usage introduces more business rules and sophistication.

To get moving forward, I'd suggest examining the links above and try coding a simple prototype to illustrate your scenario so we can discuss.

The project core team and the community can offer advice as the case may be.

**Comment by diegocgaona** [comment]
Thanks a lot elljoh!! This help me a lot.

**Comment by elljoh** [comment]
No problem. If you are affiliated with a publisher there is a `mailto:` link, ***Slack***, on http://pubfood.org/ to request an invitation to the publisher Slack channel.
