### ISSUE TITLE
pubfood on ad level not page

### ISSUE THREAD

**Issue by HDaghash** [pubfood/pubfood#38]
hello i have one question  :)
i tried to integrate with pubfood can i use pobfood on ad level not like the example ( page level);

**Comment by elljoh** [comment]
Yes, you can use pubfood at the [slot level](http://pubfood.org/api-reference#pubfood-addSlot)... if I interpret your question correctly.

Check the other examples in [examples/provider](https://github.com/pubfood/pubfood/tree/master/examples/provider). Also http://pubfood.org/quick-start illustrates the basic slot level targeting process.

**Comment by HDaghash** [comment]
thanks for the fast response , so i can to fire pubfood for each ad slot not once in the page ?

**Comment by elljoh** [comment]
Bid providers push bids for either slots or the page as a whole.

The bids pushed are assembled into targeting for the auction provider.

The auction provider would submit a request to your ad server with all slot and page bids together; generally this is what you'd do, but an auction provider can implement any logic to submit requests.

![pubfood overview](https://github.com/pubfood/pubfood/blob/master/doc/pubfood-overview.png?raw=true)

**Comment by HDaghash** [comment]
many thanks :+1:
