### ISSUE TITLE
Add a bidParams property to slots

### ISSUE THREAD

**Issue by premesh** [pubfood/pubfood#6]
Would be great to have the slot object include an option bidder parameters property. If you had this you could then pass bidder placement ids directly into the addSlot method and access them in each of the BidderProviders as needed. Great way to support an open ended amount of slot level configs that a provider may need rather than having to build  a parameter map in each bidder provider .

```
 pf.addSlot({
             name: name,
             sizes: dimensions,
             elementId: divId,
             bidProviders: providerMap[divId] || [],
             params: {openx-id:xxx}
         });
```

**Comment by elljoh** [comment]
Formalizing properties such as `params` and `targeting` is likely where we're headed. We'll keep #6 open and mark as an enhancement.

In the immediate term, before the api is formalized, you can simply use your own custom property declarations when creating a slot e.g.

```
    var CUSTOM_CONFIG = {
      name: '/id/s1',
      elementId: 'elId',
      sizes: [[50, 50]],
      bidProviders: ['bp1'],
      slotParams: {
        p1: 'v1'
      }
    };

    var slot = Slot.fromObject(CUSTOM_CONFIG);
```

If you specify custom properties to the slot object as above, I'd suggest you namespace the property name e.g. `xyz-params:`. It's possible, albeit unlikely, that there could be naming collision with any property that is defined in the formal api.

**Comment by premesh** [comment]
thanks @elljoh . How would i access those properties once set this way?

**Comment by elljoh** [comment]
You would access the property as a direct member of the slot e.g. I added this fork example:
https://github.com/elljoh/pubfood/blob/slot-custom-params/test/model/slot.js#L94-L109
