### ISSUE TITLE
Why `hasOwnProperty` for validation vs `in`?

### ISSUE THREAD

**Issue by azhang** [pubfood/pubfood#76]
https://github.com/pubfood/pubfood/blob/master/dist/pubfood.js#L3483

My implementation involves calling `pf.addBidProvider(bidProvider)` with an object that has inherited properties for `name`, `init`, and `refresh`. Therefore, it does not validate, until I copy the inherited properties into the bidProvider object itself.
```
this.name = this.name
this.init = this.init
this.refresh = this.refresh
```

Can someone explain the reasoning behind using `hasOwnProperty` rather than just using `'name' in bidProvider`?

**Comment by elljoh** [comment]
Yes, [util.js#L161](https://github.com/pubfood/pubfood/blob/master/src/util.js#L161) is a little strict I think.

I expect `hasProp = !!obj[k]` should suffice.

iirc, the reasoning for `hasOwnProperty` is legacy, but not 💯. Will pickaxe the commit log for reference, but in principle, simply checking for the existence of the property should be fine.

Do you have a workaround in the immediate/short term?

**Comment by azhang** [comment]
Thanks! Yup, copying the inherited properties into the bidProvider object itself works for now (snippet in original post). It just looks really strange at first glance!
