### ISSUE TITLE
Deals in pubfood

### ISSUE THREAD

**Issue by ffeast** [pubfood/pubfood#82]
Hi

Is there any support for deals in pubfood? 
Thanks

**Comment by elljoh** [comment]
Hiya @ffeast, regarding 

> deals

do you mean the ability to specify something like a `dealId` in bid and ad requests?

If so, yes it is possible to specify this in [BidProvider](http://pubfood.org/api-reference#pubfood-provider-BidProvider), [AuctionProvider](http://pubfood.org/api-reference#pubfood-provider-AuctionProvider) or [Slot](http://pubfood.org/api-reference#pubfood-model-Slot) configuration parameters.

Alternatively, there is also the ability to augment bid responses before they are made available for ad server targeting. See also:

- http://pubfood.org/api-reference#pubfood-addBidTransform
- http://pubfood.org/api-reference#pubfood-addRequestTransform

The general concept of transforms can be seen in this diagram:
![Pubfood Overview](https://raw.githubusercontent.com/pubfood/pubfood/master/doc/pubfood-overview.png)

**Comment by elljoh** [comment]
It is possible you refer to something like http://prebid.org/adops/deals.html and Prebid.js.

If this is the case, `DealID` targeting is a straightforward targeting key/value when pushing a bid to pubfood. Examples such as those below, _and the others_:

* [examples/provider/bid/pulsepoint/pulsepoint.html#L120-L129](https://github.com/pubfood/pubfood/blob/master/examples/provider/bid/pulsepoint/pulsepoint.html#L120-L129)
* [examples/provider/bid/audience-network/src/audience-network-bid-delegate.js#L94-L107](https://github.com/pubfood/pubfood/blob/master/examples/provider/bid/audience-network/src/audience-network-bid-delegate.js#L94-L107)

In the examples above, notice the `targeting` property is an object itself i.e. `{ targeting: {} }`. Any key/value in the targeting property (_`pushbid({})` creates a Bid and sets [Bid.targeting](https://github.com/pubfood/pubfood/blob/master/src/model/bid.js#L34)_) becomes part of the publisher ad server (e.g. DFP) request targeting slot custom parameters.

For example, note the [fb_placementid](https://github.com/pubfood/pubfood/blob/master/examples/provider/bid/audience-network/src/audience-network-bid-delegate.js#L102) bid property. Deal Id support can be added in the same way i.e. if a bid response includes deal Id targeting parameters, these can be added to the bid targeting just as in the Audience Network and other examples.

Hope this helps.
